name: ci-cd
on:
  push:
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - ".gitignore"
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      LEIN_ROOT: "true"
      CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
      CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      COGNITO_TESTS_SUB: ${{ secrets.COGNITO_TESTS_SUB }}
      COGNITO_TESTS_USERNAME: ${{ secrets.COGNITO_TESTS_USERNAME }}
      COGNITO_TESTS_PASSWORD: ${{ secrets.COGNITO_TESTS_PASSWORD }}
      COGNITO_TESTS_AUDIENCE: ${{ secrets.COGNITO_TESTS_AUDIENCE }}
      COGNITO_TESTS_ISSUER_URL: ${{ secrets.COGNITO_TESTS_ISSUER_URL }}
      COGNITO_TESTS_JWKS_URI: ${{ secrets.COGNITO_TESTS_JWKS_URI }}
      COGNITO_TESTS_USER_POOL_CLIENT_ID: ${{ secrets.COGNITO_TESTS_USER_POOL_CLIENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          lein: 2.9.8

      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2023.04.14'

      - name: Check formatting
        run: lein cljfmt check

      - name: Lint
        run: clj-kondo --lint src --lint test && lein eastwood

      - name: Test
        run: lein test :all

      - name: Deploy Jar to Clojars
        if: contains(github.ref, 'refs/tags/')
        run: lein deploy
